### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by kurokirasama** [zvovov/whatsapp-web#20]
Hello, i'm getting this error:

```
File "chat.py", line 249
    sys.exit(print(e, decorateMsg("\n\tChromedriver Error. Read the above error (if any), then\n\tCheck if installed chromedriver version is compatible with installed Chrome version.", bcolors.WARNING)))
                 ^
SyntaxError: invalid syntax
```

**Comment by kurokirasama** [comment]
OK, i commented line 249 and 250, chrome opened, scan the qr code and logged into my whatsapp account. In cli I got:

	```
Phone connected? y/n: y
Traceback (most recent call last):
  File "chat.py", line 240, in <module>
    main()
  File "chat.py", line 66, in main
    isConnected = input(decorateMsg("\n\tPhone connected? y/n: ", bcolors.HEADER))
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
user@Ubuntu:~/software/whatsapp-w
```

**Comment by zvovov** [comment]
#7
Use python 3
