### ISSUE TITLE
it works... but it doesn't - able to connect and send first message but then throws exceptions

### ISSUE THREAD

**Issue by cherkie** [zvovov/whatsapp-web#23]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/albert/whatsapp-web/chat.py", line 119, in startGetMsg
    incoming_scheduler.run()
  File "/usr/lib/python3.5/sched.py", line 147, in run
    action(*argument, **kwargs)
  File "/home/albert/whatsapp-web/chat.py", line 129, in getMsg
    curr_thread_name = printThreadName(driver)
  File "/home/albert/whatsapp-web/chat.py", line 222, in printThreadName
    curr_thread_name = driver.find_element(By.XPATH, '//*[@id="main"]/header//span[contains(@dir, "auto")]').text
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 744, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 231, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/remote_connection.py", line 425, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1142, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 975, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent

after that whatever I type manages to go through to recipient but the script is otherwise broken, unable to receive messages.

**Comment by tomasi-o** [comment]
I got a similar error but I am at least able to send messages using the `send to` command. Anybody else with this issue?

**Comment by zvovov** [comment]
@cherkie The code has been updated and should work now. If you're still facing this issue please post your OS, selenium, and webdriver version. Thanks
