### ISSUE TITLE
crash when pressing 'y'

### ISSUE THREAD

**Issue by anabis** [zvovov/whatsapp-web#25]
I did wait after scanning the QR code.
`hugo@brun:~/sources$ python whatsapp-web/chat.py yas

	Phone connected? y/n: y
Traceback (most recent call last):
  File "whatsapp-web/chat.py", line 240, in <module>
    main()
  File "whatsapp-web/chat.py", line 66, in main
    isConnected = input(decorateMsg("\n\tPhone connected? y/n: ", bcolors.HEADER))
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
`

**Comment by y0l016** [comment]
I have the same issue. I also had an issue at line 249 ayntax error. Then i've removed lines 248,249. After that I get this error. But I guess removing lines 248,249 is not a cause of this problem. I'm waiting for your fix.

**Comment by Demiurgo443** [comment]
When pressing 'y' I have instead this error:

Phone connected? y/n: ←[0my
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="side"]//input"}
  (Session info: chrome=83.0.4103.116)
 ←[93m
        Chromedriver Error. Read the above error (if any), then
        Check if installed chromedriver version is compatible with installed Chrome version.←[0m

However the executable of Chromedriver is the right one.

**Comment by zvovov** [comment]
Closing due to inactivity
